steps:
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    secretEnv: [
        "MYSQLHOST",
        "MYSQLPASSWORD",
        "MYSQLUSER",
      ]
    entrypoint: "bash"
    args:
      - -c
      - |
        echo $'\n  MYSQLHOST: '$$MYSQLHOST >> app.yaml
        echo $'\n  MYSQLPASSWORD: '$$MYSQLPASSWORD >> app.yaml
        echo $'\n  MYSQLUSER: '$$MYSQLUSER >> app.yaml
        gcloud config set app/cloud_build_timeout 1600
        gcloud app deploy
        gcloud app browse
timeout: "1600s"
availableSecrets:
  secretManager:
    - versionName: projects/637632514001/secrets/MYSQLHOST/versions/1
      env: "MYSQLHOST"
    - versionName: projects/637632514001/secrets/MYSQLPASSWORD/versions/1
      env: "MYSQLPASSWORD"
    - versionName: projects/637632514001/secrets/MYSQLUSER/versions/1
      env: "MYSQLUSER"
